kind: Service
apiVersion: v1
metadata:
  name: concierge
spec:
  selector:
    app: goophr
    component: concierge
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
    nodePort: 30090
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: concierge-deployment
  labels:
    app: goophr
    component: concierge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goophr
      component: concierge
  template:
    metadata:
      labels:
        app: goophr
        component: concierge
    spec:
      containers:
      - name: concierge
        image: goophr_concierge
        imagePullPolicy: Never
        ports:
        - containerPort: 9090
        env:
        - name: API_PORT
          value: "9090"
        - name: LIB_A_M
          value: a-m-librarian/api
        - name: LIB_N_Z
          value: n-z-librarian/api
        - name: LIB_OTHERS
          value: others-librarian/api
