kind: Service
apiVersion: v1
metadata:
  name: file-server
spec:
  selector:
    app: goophr
    component: file-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9876
    nodePort: 30876
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: file-server-deployment
  labels:
    app: goophr
    component: file-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goophr
      component: file-server
  template:
    metadata:
      labels:
        app: goophr
        component: file-server
    spec:
      containers:
      - name: file-server
        image: goophr_file_server
        imagePullPolicy: Never
        ports:
        - containerPort: 9876

