kind: Service
apiVersion: v1
metadata:
  name: others-librarian
spec:
  selector:
    app: goophr
    component: librarian
    range: others
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: others-librarian-deployment
  labels:
    app: goophr
    component: librarian
    range: others
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goophr
      component: librarian
      range: others
  template:
    metadata:
      labels:
        app: goophr
        component: librarian
        range: others
    spec:
      containers:
      - name: others-librarian
        image: goophr_librarian
        imagePullPolicy: Never
        env:
        - name: API_PORT
          value: "8080"
        ports:
        - containerPort: 8080
